// src/micro-apps/home/components/Contact.vue
<template>
  <section id="contact" :class="$style.section">
    <div :class="$style.container">
      <div :class="$style.heading">
        <h2 :class="$style.title">İletişim</h2>
        <p :class="$style.subtitle">
          Yeni projeler, işbirlikleri ve fikirleriniz için iletişime geçmekten çekinmeyin!
        </p>
      </div>

      <div :class="$style.cardWrapper">
        <div :class="$style.card">
          <div :class="$style.mailSection">
            <div :class="$style.mailIcon">
              <i class="ri-mail-line" aria-hidden="true" />
            </div>
            <p :class="$style.mailText">
              Projeleriniz, işbirliği teklifleriniz veya sorularınız için bana ulaşabilirsiniz.
            </p>
            <a href="mailto:yasinatesim@gmail.com" :class="$style.mailLink">
              yasinatesim@gmail.com
            </a>
          </div>

          <div :class="$style.socialSection">
            <h3 :class="$style.socialTitle">Sosyal Medya</h3>
            <div :class="$style.socialList">
              <a
                v-for="link in socialLinks"
                :key="link.href"
                :href="link.href"
                target="_blank"
                rel="noopener noreferrer"
                :aria-label="link.label"
                :class="[$style.socialLink, $style[link.styleKey]]"
              >
                <i :class="link.icon" aria-hidden="true" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const socialLinks = [
  { href: 'https://github.com/yasinatesim',   label: 'GitHub',    icon: 'ri-github-fill',    styleKey: 'socialGithub' },
  { href: 'https://linkedin.com/in/yasinatesim', label: 'LinkedIn', icon: 'ri-linkedin-fill', styleKey: 'socialLinkedin' },
  { href: 'https://instagram.com/yasinatesim', label: 'Instagram', icon: 'ri-instagram-fill', styleKey: 'socialInstagram' },
  { href: 'https://twitter.com/yasinatesim',  label: 'X',         icon: 'ri-twitter-x-fill', styleKey: 'socialX' },
  { href: 'https://medium.com/@yasinatesim',  label: 'Medium',    icon: 'ri-medium-fill',    styleKey: 'socialMedium' },
  { href: 'https://dev.to/yasinatesim',       label: 'DEV.to',    icon: 'ri-code-box-fill',  styleKey: 'socialDevto' },
]
</script>

<style module>
.section {
  padding: var(--space-20) 0;
  background-color: var(--color-indigo-50);
}
.container {
  max-width: var(--container-max);
  margin: 0 auto;
  padding: 0 var(--space-4);
}
.heading { text-align: center; margin-bottom: var(--space-16); }
.title {
  font-size: var(--font-size-4xl);
  font-weight: 800;
  margin-bottom: var(--space-4);
  color: var(--color-primary);
}
.subtitle {
  color: var(--color-gray-600);
  max-width: 42rem;
  margin: 0 auto;
  font-size: var(--font-size-lg);
}
.cardWrapper { max-width: 36rem; margin: 0 auto; }
.card {
  background-color: rgba(255,255,255,0.8);
  backdrop-filter: blur(16px);
  border-radius: var(--radius-2xl);
  box-shadow: var(--shadow-lg);
  padding: var(--space-8);
  border: 1px solid rgba(59,130,246,0.1);
}
.mailSection {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-bottom: var(--space-10);
}
.mailIcon {
  width: 3.5rem;
  height: 3.5rem;
  border-radius: var(--radius-full);
  background-color: rgba(59,130,246,0.9);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: var(--space-4);
  color: var(--color-white);
  font-size: var(--font-size-2xl);
}
.mailText { font-size: var(--font-size-base); color: var(--color-gray-700); margin-bottom: var(--space-2); text-align: center; }
.mailLink { font-size: var(--font-size-lg); font-weight: var(--font-weight-medium); color: var(--color-primary); }
.mailLink:hover { text-decoration: underline; }
.socialSection { display: flex; flex-direction: column; align-items: center; }
.socialTitle { font-size: var(--font-size-lg); font-weight: var(--font-weight-semibold); margin-bottom: var(--space-5); color: #000; }
.socialList { display: flex; flex-wrap: wrap; justify-content: center; gap: var(--space-3); }
.socialLink {
  width: 2.75rem;
  height: 2.75rem;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-full);
  background-color: var(--color-white);
  box-shadow: var(--shadow-sm);
  text-decoration: none;
  font-size: var(--font-size-xl);
  transition: background-color 0.2s, color 0.2s;
}
.socialGithub    { border: 1px solid #e5e7eb; color: #374151; }
.socialGithub:hover    { background-color: #111827; color: var(--color-white); }
.socialLinkedin  { border: 1px solid #dbeafe; color: #1d4ed8; }
.socialLinkedin:hover  { background-color: #1d4ed8; color: var(--color-white); }
.socialInstagram { border: 1px solid #fce7f3; color: #db2777; }
.socialInstagram:hover { background-color: #db2777; color: var(--color-white); }
.socialX         { border: 1px solid #e5e7eb; color: #111827; }
.socialX:hover         { background-color: #000; color: var(--color-white); }
.socialMedium    { border: 1px solid #e5e7eb; color: #374151; }
.socialMedium:hover    { background-color: #1f2937; color: var(--color-white); }
.socialDevto     { border: 1px solid #e5e7eb; color: #000; }
.socialDevto:hover     { background-color: #000; color: var(--color-white); }
</style>

// src/components/Home/Contact.tsx
import styles from './Contact.module.scss'

const socialLinks = [
  {
    href: 'https://github.com/yasinatesim',
    label: 'GitHub',
    colorClass: styles.socialGithub,
    icon: <i className="ri-github-fill" aria-hidden="true" />,
  },
  {
    href: 'https://linkedin.com/in/yasinatesim',
    label: 'LinkedIn',
    colorClass: styles.socialLinkedin,
    icon: <i className="ri-linkedin-fill" aria-hidden="true" />,
  },
  {
    href: 'https://instagram.com/yasinatesim',
    label: 'Instagram',
    colorClass: styles.socialInstagram,
    icon: <i className="ri-instagram-fill" aria-hidden="true" />,
  },
  {
    href: 'https://twitter.com/yasinatesim',
    label: 'X',
    colorClass: styles.socialX,
    icon: (
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 32 32" fill="none" aria-hidden="true">
        <path d="M19.615 13.295 28.045 4h-2.13l-7.36 8.255L12.01 4H4.5l8.77 12.515L4.5 28h2.13l7.77-8.715L19.99 28h7.51l-7.885-14.705ZM6.97 5.522h4.18l13.09 20.956h-4.18L6.97 5.522Z" fill="currentColor" />
      </svg>
    ),
  },
  {
    href: 'https://medium.com/@yasinatesim',
    label: 'Medium',
    colorClass: styles.socialMedium,
    icon: (
      <svg width="26" height="26" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <ellipse cx="5.5" cy="12" rx="4.5" ry="7" fill="currentColor" />
        <ellipse cx="18" cy="12" rx="2" ry="7" fill="currentColor" />
        <ellipse cx="12" cy="12" rx="2.5" ry="7" fill="currentColor" />
      </svg>
    ),
  },
  {
    href: 'https://dev.to/yasinatesim',
    label: 'DEV.to',
    colorClass: styles.socialDevto,
    icon: (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <path d="M7.826 10.083a.784.784 0 0 0-.468-.175h-.701v4.198h.701a.786.786 0 0 0 .469-.175c.155-.117.233-.292.233-.525v-2.798c.001-.233-.079-.408-.234-.525zM19.236 3H4.764C3.791 3 3.002 3.787 3 4.76v14.48c.002.973.791 1.76 1.764 1.76h14.473c.973 0 1.762-.787 1.764-1.76V4.76A1.765 1.765 0 0 0 19.236 3zM9.195 13.414c0 .755-.466 1.901-1.942 1.898H5.389V8.665h1.903c1.424 0 1.902 1.144 1.903 1.899v2.85zm4.045-3.562H11.1v1.544h1.309v1.188H11.1v1.543h2.142v1.188h-2.498a.813.813 0 0 1-.833-.792V9.497a.813.813 0 0 1 .792-.832h2.539l-.002 1.187zm4.165 4.632c-.531 1.235-1.481.99-1.906 0l-1.548-5.818h1.309l1.193 4.569 1.188-4.569h1.31l-1.546 5.818z" />
      </svg>
    ),
  },
]

const Contact = () => {
  return (
    <section id="contact" className={styles.section}>
      <div className={styles.container}>
        <div className={styles.heading}>
          <h2 className={styles.title}>İletişim</h2>
          <p className={styles.subtitle}>Yeni projeler, işbirlikleri ve fikirleriniz için iletişime geçmekten çekinmeyin!</p>
        </div>
        <div className={styles.cardWrapper}>
          <div className={styles.card}>
            <div className={styles.mailSection}>
              <div className={styles.mailIcon}>
                <i className="ri-mail-line" aria-hidden="true" />
              </div>
              <p className={styles.mailText}>
                Projeleriniz, işbirliği teklifleriniz veya sorularınız için bana ulaşabilirsiniz.
              </p>
              <a href="mailto:yasinatesim@gmail.com" className={styles.mailLink}>
                yasinatesim@gmail.com
              </a>
            </div>
            <div className={styles.socialSection}>
              <h3 className={styles.socialTitle}>Sosyal Medya</h3>
              <div className={styles.socialList}>
                {socialLinks.map(({ href, label, colorClass, icon }) => (
                  <a
                    key={href}
                    href={href}
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label={label}
                    className={`${styles.socialLink} ${colorClass}`}
                  >
                    {icon}
                  </a>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Contact
